CREATE DATABASE UNOESC_BANK;

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUM_CONTA VARCHAR(10),
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_ID_CLIENTE_CONTA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);



