-- CRIAR NOVO BD

CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O BD

USE GREENHOUSE;

-- CRIANDO UMA TABELA

CREATE TABLE `GREENHOUSE` . `PLANTS` 
(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Orquidea', 10, 'HIGH');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Rosa', 5, 'LOW');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('BAMBU', 3, 'LOW');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('JACARANDA', 63, 'HIGH');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('JAQUEIRA', 942, 'HIGH');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('CENOURA', 234, 'LOW');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('SUCULENTA', 412366, 'HIGH');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('VIOLETA', 6662, 'HIGH');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('JADE', 123342, 'LOW');

INSERT INTO `GREENHOUSE` . `PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('CACTO', 80085, 'LOW');

-- VER TUDO DA TABELA
SELECT * FROM `GREENHOUSE` . `PLANTS`;

-- ESPECIFICANDO APENAS AS COLUNAS DESEJADAS

SELECT `PLANT_NAME`, `SENSOR_EVENT` FROM `PLANTS`; 

-- APLICANDO FILTROS NOS REGISTROS DE DADOS (*/ω＼*)

SELECT * FROM PLANTS WHERE `SENSOR_LEVEL` = "HIGH" AND `SENSOR_VALUE` <= 20;

SELECT * FROM PLANTS where SENSOR_LEVEL IN ("HIGH" , "LOW");

-- CLAUSULA DE ORDENAÇão
SELECT * FROM PLANTS WHERE SENSOR_VALUE > 420 ORDER BY SENSOR_VALUE DESC;

-- FUNCOES DE AGRUPAMENTO

SELECT COUNT(*), SENSOR_LEVEL FROM PLANTS GROUP BY SENSOR_LEVEL;

-- select top

SELECT `PLANT_NAME` FROM `PLANTS` WHERE `SENSOR_LEVEL` = "LOW" LIMIT 2;

-- AVG
SELECT AVG(`SENSOR_VALUE`) FROM `PLANTS`;
SELECT MIN(`SENSOR_VALUE`)FROM `PLANTS`;
SELECT MAX(`SENSOR_VALUE`)FROM `PLANTS`;
SELECT SUM(`SENSOR_VALUE`)FROM `PLANTS`;

-- comando para atualizar registros de dados

SELECT * FROM PLANTS;
UPDATE PLANTS SET SENSOR_VALUE = 90, SENSOR_LEVEL = "HIGH" WHERE PLANT_NAME = "BAMBU";

DELETE FROM PLANTS WHERE PLANT_NAME = "rosa";


